// Dados dos projetos do portfólio
export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    title: "BRAHMA OAB",
    category: "Evento Corporativo",
    image: "/images/portfolio/BRAHMA OAB/img_brahma_oab1.JPG",
    video: "/videos/reels/BRAHMA OAB/video_brahma_oab.mp4",
    description: "Cenografia impactante para evento corporativo",
    images: [
      "/images/portfolio/BRAHMA OAB/img_brahma_oab1.JPG",
      "/images/portfolio/BRAHMA OAB/img_brahma_oab2.JPG",
      "/images/portfolio/BRAHMA OAB/img_brahma_oab3.JPG",
    ],
  },
  {
    id: 2,
    title: "CDBAR - Tema RJ",
    category: "Ativação",
    image: "/images/portfolio/CDBAR _Tema Rj/img_cdbar_rio2.JPG",
    video: "/videos/reels/CDBAR _Tema Rj/video_cdbar_rio.mp4",
    description: "Experiência imersiva temática",
    images: [
      "/images/portfolio/CDBAR _Tema Rj/img_cdbar_rio2.JPG",
      "/images/portfolio/CDBAR _Tema Rj/img_cdbar_rio3.JPG",
      "/images/portfolio/CDBAR _Tema Rj/img_cdbar_rio4.JPG",
    ],
  },
  {
    id: 3,
    title: "Festival PRIMAVERÃO",
    category: "Festival",
    image: "/images/portfolio/Festival PRIMAVERÃO/img_festialprimaverao1.JPG",
    video: "/videos/reels/Festival PRIMAVERÃO/video_festivalprimaverao.mp4",
    description: "Grande produção para festival",
    images: [
      "/images/portfolio/Festival PRIMAVERÃO/img_festialprimaverao1.JPG",
      "/images/portfolio/Festival PRIMAVERÃO/img_festialprimaverao2.JPG",
      "/images/portfolio/Festival PRIMAVERÃO/img_festialprimaverao3.JPG",
    ],
  },
  {
    id: 4,
    title: "MBA Experience 2023",
    category: "Educacional",
    image: "/images/portfolio/MBA Experience 2023/img_mba23_1.PNG",
    video: "/videos/reels/MBA Experience 2023/video_mba23.mp4",
    description: "Cenografia para evento educacional",
    images: [
      "/images/portfolio/MBA Experience 2023/img_mba23_1.PNG",
      "/images/portfolio/MBA Experience 2023/img_mba23_2.PNG",
      "/images/portfolio/MBA Experience 2023/img_mba23_3.PNG",
    ],
  },
  {
    id: 5,
    title: "STAND PILAR 2026",
    category: "Stand",
    image: "/images/portfolio/STAND_PILAR_2026/IMAGEM_STAND1.jpeg",
    video: "/videos/reels/STAND_PILAR_2026/VIDEO_STAND_PILAR.mp4",
    description: "Stand cenográfico para feira",
    images: [
      "/images/portfolio/STAND_PILAR_2026/IMAGEM_STAND1.jpeg",
      "/images/portfolio/STAND_PILAR_2026/IMAGEM_STAND2.jpeg",
      "/images/portfolio/STAND_PILAR_2026/IMAGEM_STAND3.jpeg",
    ],
  },
  {
    id: 6,
    title: "Tardezinha do Sabores 2",
    category: "Social",
    image: "/images/portfolio/Tardezinha do Sabores 2/img_tardezinha1.JPG",
    video: "/videos/reels/Tardezinha do Sabores 2/video_tardezinha.mp4",
    description: "Evento social com cenografia",
    images: [
      "/images/portfolio/Tardezinha do Sabores 2/img_tardezinha1.JPG",
      "/images/portfolio/Tardezinha do Sabores 2/img_tardezinha2.JPG",
      "/images/portfolio/Tardezinha do Sabores 2/img_tardezinha3.JPG",
    ],
  },
]
